// Auto-generated AI test stimulus for RISC-V ALU
// 56 test vectors generated by Claude (Anthropic)
// These can be included in a UVM sequence body() task

// Test 1: ADD: max positive + 1, triggers signed overflow
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h7FFFFFFF;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd0;
finish_item(item);

// Test 2: ADD: max_pos + max_pos, large signed overflow
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h7FFFFFFF;
item.operand_b = 32'h7FFFFFFF;
item.alu_op    = 4'd0;
finish_item(item);

// Test 3: ADD: min_neg + min_neg, signed overflow with carry
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h80000000;
item.alu_op    = 4'd0;
finish_item(item);

// Test 4: ADD: all_ones + 1, carry out, result wraps to zero
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd0;
finish_item(item);

// Test 5: ADD: zero + zero, all flags clear
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000000;
item.operand_b = 32'h00000000;
item.alu_op    = 4'd0;
finish_item(item);

// Test 6: ADD: 1 + all_ones, carry and zero result
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'hFFFFFFFF;
item.alu_op    = 4'd0;
finish_item(item);

// Test 7: ADD: min_neg + max_pos, result is all_ones
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h7FFFFFFF;
item.alu_op    = 4'd0;
finish_item(item);

// Test 8: ADD: two positive values causing overflow
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h40000000;
item.operand_b = 32'h40000000;
item.alu_op    = 4'd0;
finish_item(item);

// Test 9: SUB: min_neg - 1, signed overflow
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd1;
finish_item(item);

// Test 10: SUB: zero - 1, borrow/carry, result is all_ones
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000000;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd1;
finish_item(item);

// Test 11: SUB: max_pos - all_ones (max_pos - (-1))
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h7FFFFFFF;
item.operand_b = 32'hFFFFFFFF;
item.alu_op    = 4'd1;
finish_item(item);

// Test 12: SUB: zero - min_neg, signed overflow
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000000;
item.operand_b = 32'h80000000;
item.alu_op    = 4'd1;
finish_item(item);

// Test 13: SUB: zero - zero, zero result
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000000;
item.operand_b = 32'h00000000;
item.alu_op    = 4'd1;
finish_item(item);

// Test 14: SUB: min_neg - max_pos, massive overflow
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h7FFFFFFF;
item.alu_op    = 4'd1;
finish_item(item);

// Test 15: SUB: all_ones - all_ones, zero result
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'hFFFFFFFF;
item.alu_op    = 4'd1;
finish_item(item);

// Test 16: SUB: 1 - min_neg, signed overflow
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'h80000000;
item.alu_op    = 4'd1;
finish_item(item);

// Test 17: AND: all_ones & zero = zero
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'h00000000;
item.alu_op    = 4'd2;
finish_item(item);

// Test 18: AND: all_ones & all_ones = all_ones
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'hFFFFFFFF;
item.alu_op    = 4'd2;
finish_item(item);

// Test 19: AND: min_neg & max_pos = zero (no overlap)
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h7FFFFFFF;
item.alu_op    = 4'd2;
finish_item(item);

// Test 20: AND: alternating patterns, zero result
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hA5A5A5A5;
item.operand_b = 32'h5A5A5A5A;
item.alu_op    = 4'd2;
finish_item(item);

// Test 21: AND: one & one = one
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd2;
finish_item(item);

// Test 22: OR: zero | zero = zero
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000000;
item.operand_b = 32'h00000000;
item.alu_op    = 4'd3;
finish_item(item);

// Test 23: OR: min_neg | max_pos = all_ones
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h7FFFFFFF;
item.alu_op    = 4'd3;
finish_item(item);

// Test 24: OR: all_ones | one = all_ones
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd3;
finish_item(item);

// Test 25: OR: one | min_neg, negative result
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'h80000000;
item.alu_op    = 4'd3;
finish_item(item);

// Test 26: OR: alternating patterns = all_ones
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hA5A5A5A5;
item.operand_b = 32'h5A5A5A5A;
item.alu_op    = 4'd3;
finish_item(item);

// Test 27: XOR: all_ones ^ all_ones = zero
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'hFFFFFFFF;
item.alu_op    = 4'd4;
finish_item(item);

// Test 28: XOR: zero ^ all_ones = all_ones
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000000;
item.operand_b = 32'hFFFFFFFF;
item.alu_op    = 4'd4;
finish_item(item);

// Test 29: XOR: min_neg ^ one
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd4;
finish_item(item);

// Test 30: XOR: max_pos ^ min_neg = all_ones
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h7FFFFFFF;
item.operand_b = 32'h80000000;
item.alu_op    = 4'd4;
finish_item(item);

// Test 31: XOR: one ^ one = zero
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd4;
finish_item(item);

// Test 32: SLL: shift 1 by 0, no change
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'h00000000;
item.alu_op    = 4'd5;
finish_item(item);

// Test 33: SLL: shift 1 by 31, becomes min_neg
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'h0000001F;
item.alu_op    = 4'd5;
finish_item(item);

// Test 34: SLL: shift min_neg by 1, becomes zero
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd5;
finish_item(item);

// Test 35: SLL: shift all_ones by 1
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd5;
finish_item(item);

// Test 36: SLL: shift max_pos by 31
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h7FFFFFFF;
item.operand_b = 32'h0000001F;
item.alu_op    = 4'd5;
finish_item(item);

// Test 37: SRL: shift min_neg right by 31, becomes 1
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h0000001F;
item.alu_op    = 4'd6;
finish_item(item);

// Test 38: SRL: logical right shift all_ones by 1
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd6;
finish_item(item);

// Test 39: SRL: shift 1 right by 1, becomes zero
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd6;
finish_item(item);

// Test 40: SRL: shift min_neg by 0, no change
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h00000000;
item.alu_op    = 4'd6;
finish_item(item);

// Test 41: SRL: shift max_pos right by 31, becomes zero
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h7FFFFFFF;
item.operand_b = 32'h0000001F;
item.alu_op    = 4'd6;
finish_item(item);

// Test 42: SRA: arithmetic shift min_neg by 31, becomes all_ones
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h0000001F;
item.alu_op    = 4'd7;
finish_item(item);

// Test 43: SRA: arithmetic shift max_pos by 31, becomes zero
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h7FFFFFFF;
item.operand_b = 32'h0000001F;
item.alu_op    = 4'd7;
finish_item(item);

// Test 44: SRA: arithmetic shift all_ones by 1, stays all_ones
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd7;
finish_item(item);

// Test 45: SRA: arithmetic shift min_neg by 1, sign extends
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd7;
finish_item(item);

// Test 46: SRA: shift 1 by 0, no change
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'h00000000;
item.alu_op    = 4'd7;
finish_item(item);

// Test 47: SLT: -1 < 1 signed, result = 1
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd8;
finish_item(item);

// Test 48: SLT: 1 < -1 signed, result = 0
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'hFFFFFFFF;
item.alu_op    = 4'd8;
finish_item(item);

// Test 49: SLT: min_neg < max_pos signed, result = 1
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h7FFFFFFF;
item.alu_op    = 4'd8;
finish_item(item);

// Test 50: SLT: max_pos < min_neg signed, result = 0
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h7FFFFFFF;
item.operand_b = 32'h80000000;
item.alu_op    = 4'd8;
finish_item(item);

// Test 51: SLT: zero < zero, result = 0
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000000;
item.operand_b = 32'h00000000;
item.alu_op    = 4'd8;
finish_item(item);

// Test 52: SLTU: max_unsigned < 1, result = 0 (opposite of SLT)
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'hFFFFFFFF;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd9;
finish_item(item);

// Test 53: SLTU: 1 < max_unsigned, result = 1 (opposite of SLT)
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000001;
item.operand_b = 32'hFFFFFFFF;
item.alu_op    = 4'd9;
finish_item(item);

// Test 54: SLTU: 0x80000000 > 0x7FFFFFFF unsigned, result = 0
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h80000000;
item.operand_b = 32'h7FFFFFFF;
item.alu_op    = 4'd9;
finish_item(item);

// Test 55: SLTU: zero < one, result = 1
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h00000000;
item.operand_b = 32'h00000001;
item.alu_op    = 4'd9;
finish_item(item);

// Test 56: SLTU: max_pos < min_neg unsigned, result = 1
item = alu_seq_item::type_id::create("item");
start_item(item);
item.operand_a = 32'h7FFFFFFF;
item.operand_b = 32'h80000000;
item.alu_op    = 4'd9;
finish_item(item);

