#!/usr/bin/env python3
"""
AI-Assisted Test Generation for RISC-V RV32I ALU
Compares AI-generated test vectors against constrained random testing
to demonstrate how targeted AI stimulus can improve verification coverage.

The AI test vectors were generated by prompting Claude (Anthropic) with the
ALU specification and asking for coverage-maximising test cases. These are
compared against constrained random tests matching the UVM testbench distribution.

Usage:
    python ai_test_gen.py
    python ai_test_gen.py --live    (requires GEMINI_API_KEY for live generation)
"""

import json
import os
import random
import sys
from dataclasses import dataclass


# =============================================================================
# ALU Reference Model (mirrors the RTL exactly)
# =============================================================================

ALU_OPS = {
    0: "ADD", 1: "SUB", 2: "AND", 3: "OR", 4: "XOR",
    5: "SLL", 6: "SRL", 7: "SRA", 8: "SLT", 9: "SLTU"
}

MASK_32 = 0xFFFFFFFF
MASK_33 = 0x1FFFFFFFF


def to_signed_32(val):
    val &= MASK_32
    return val - 0x100000000 if val >= 0x80000000 else val


def alu_compute(op, a, b):
    a &= MASK_32
    b &= MASK_32
    add_res = (a + b) & MASK_33
    sub_res = (a - b) & MASK_33

    if op == 0:
        result = add_res & MASK_32
    elif op == 1:
        result = sub_res & MASK_32
    elif op == 2:
        result = a & b
    elif op == 3:
        result = a | b
    elif op == 4:
        result = a ^ b
    elif op == 5:
        result = (a << (b & 0x1F)) & MASK_32
    elif op == 6:
        result = (a >> (b & 0x1F)) & MASK_32
    elif op == 7:
        result = (to_signed_32(a) >> (b & 0x1F)) & MASK_32
    elif op == 8:
        result = 1 if to_signed_32(a) < to_signed_32(b) else 0
    elif op == 9:
        result = 1 if a < b else 0
    else:
        result = 0

    zero = int(result == 0)
    negative = int((result >> 31) & 1)
    carry = int((add_res >> 32) & 1) if op == 0 else int((sub_res >> 32) & 1) if op == 1 else 0

    if op == 0:
        overflow = int(((a >> 31) == (b >> 31)) and (((add_res >> 31) & 1) != ((a >> 31) & 1)))
    elif op == 1:
        overflow = int(((a >> 31) != (b >> 31)) and (((sub_res >> 31) & 1) != ((a >> 31) & 1)))
    else:
        overflow = 0

    return result, zero, overflow, carry, negative


# =============================================================================
# Test Vector Data Class
# =============================================================================

@dataclass
class TestVector:
    operand_a: int
    operand_b: int
    alu_op: int
    description: str = ""

    def verify(self):
        result, zero, overflow, carry, negative = alu_compute(
            self.alu_op, self.operand_a, self.operand_b
        )
        return {
            "op_a": f"0x{self.operand_a:08X}",
            "op_b": f"0x{self.operand_b:08X}",
            "op": ALU_OPS.get(self.alu_op, "UNKNOWN"),
            "result": f"0x{result:08X}",
            "zero": zero, "overflow": overflow,
            "carry": carry, "negative": negative,
            "description": self.description
        }


# =============================================================================
# Coverage Tracker
# =============================================================================

class CoverageTracker:
    def __init__(self):
        self.op_bins = {i: False for i in range(10)}
        boundary_vals = ["zero", "max_pos", "min_neg", "all_ones", "one", "positive", "negative"]
        self.opa_bins = {v: False for v in boundary_vals}
        self.opb_bins = {v: False for v in boundary_vals}
        self.flag_bins = {
            "zero_0": False, "zero_1": False,
            "overflow_0": False, "overflow_1": False,
            "carry_0": False, "carry_1": False,
            "negative_0": False, "negative_1": False
        }
        self.op_x_opa = {}
        self.op_x_opb = {}
        for op in range(10):
            for val in boundary_vals:
                self.op_x_opa[(op, val)] = False
                self.op_x_opb[(op, val)] = False

    def _categorise(self, val):
        val &= MASK_32
        if val == 0x00000000: return "zero"
        elif val == 0x7FFFFFFF: return "max_pos"
        elif val == 0x80000000: return "min_neg"
        elif val == 0xFFFFFFFF: return "all_ones"
        elif val == 0x00000001: return "one"
        elif val <= 0x7FFFFFFE: return "positive"
        else: return "negative"

    def sample(self, tv):
        result, zero, overflow, carry, negative = alu_compute(tv.alu_op, tv.operand_a, tv.operand_b)
        if tv.alu_op in self.op_bins:
            self.op_bins[tv.alu_op] = True
        cat_a = self._categorise(tv.operand_a)
        cat_b = self._categorise(tv.operand_b)
        self.opa_bins[cat_a] = True
        self.opb_bins[cat_b] = True
        self.flag_bins[f"zero_{zero}"] = True
        self.flag_bins[f"overflow_{overflow}"] = True
        self.flag_bins[f"carry_{carry}"] = True
        self.flag_bins[f"negative_{negative}"] = True
        if tv.alu_op in range(10):
            self.op_x_opa[(tv.alu_op, cat_a)] = True
            self.op_x_opb[(tv.alu_op, cat_b)] = True

    def get_report(self):
        def pct(d):
            return (sum(d.values()) / len(d)) * 100 if d else 0
        return {
            "operation_coverage": pct(self.op_bins),
            "operand_a_coverage": pct(self.opa_bins),
            "operand_b_coverage": pct(self.opb_bins),
            "flag_coverage": pct(self.flag_bins),
            "cross_op_x_opa": pct(self.op_x_opa),
            "cross_op_x_opb": pct(self.op_x_opb),
            "op_bins_hit": f"{sum(self.op_bins.values())}/10",
            "opa_bins_hit": f"{sum(self.opa_bins.values())}/7",
            "opb_bins_hit": f"{sum(self.opb_bins.values())}/7",
            "cross_opa_hit": f"{sum(self.op_x_opa.values())}/70",
            "cross_opb_hit": f"{sum(self.op_x_opb.values())}/70",
        }


# =============================================================================
# AI-Generated Test Vectors (generated by Claude, Anthropic)
# =============================================================================
# These vectors were produced by prompting Claude with the ALU specification
# and requesting coverage-maximising test cases targeting boundary values,
# overflow/underflow conditions, flag edge cases, and cross coverage.

AI_GENERATED_TESTS = [
    # --- ADD boundary and overflow tests ---
    (0x7FFFFFFF, 0x00000001, 0, "ADD: max positive + 1, triggers signed overflow"),
    (0x7FFFFFFF, 0x7FFFFFFF, 0, "ADD: max_pos + max_pos, large signed overflow"),
    (0x80000000, 0x80000000, 0, "ADD: min_neg + min_neg, signed overflow with carry"),
    (0xFFFFFFFF, 0x00000001, 0, "ADD: all_ones + 1, carry out, result wraps to zero"),
    (0x00000000, 0x00000000, 0, "ADD: zero + zero, all flags clear"),
    (0x00000001, 0xFFFFFFFF, 0, "ADD: 1 + all_ones, carry and zero result"),
    (0x80000000, 0x7FFFFFFF, 0, "ADD: min_neg + max_pos, result is all_ones"),
    (0x40000000, 0x40000000, 0, "ADD: two positive values causing overflow"),

    # --- SUB boundary and underflow tests ---
    (0x80000000, 0x00000001, 1, "SUB: min_neg - 1, signed overflow"),
    (0x00000000, 0x00000001, 1, "SUB: zero - 1, borrow/carry, result is all_ones"),
    (0x7FFFFFFF, 0xFFFFFFFF, 1, "SUB: max_pos - all_ones (max_pos - (-1))"),
    (0x00000000, 0x80000000, 1, "SUB: zero - min_neg, signed overflow"),
    (0x00000000, 0x00000000, 1, "SUB: zero - zero, zero result"),
    (0x80000000, 0x7FFFFFFF, 1, "SUB: min_neg - max_pos, massive overflow"),
    (0xFFFFFFFF, 0xFFFFFFFF, 1, "SUB: all_ones - all_ones, zero result"),
    (0x00000001, 0x80000000, 1, "SUB: 1 - min_neg, signed overflow"),

    # --- AND tests with boundary values ---
    (0xFFFFFFFF, 0x00000000, 2, "AND: all_ones & zero = zero"),
    (0xFFFFFFFF, 0xFFFFFFFF, 2, "AND: all_ones & all_ones = all_ones"),
    (0x80000000, 0x7FFFFFFF, 2, "AND: min_neg & max_pos = zero (no overlap)"),
    (0xA5A5A5A5, 0x5A5A5A5A, 2, "AND: alternating patterns, zero result"),
    (0x00000001, 0x00000001, 2, "AND: one & one = one"),

    # --- OR tests with boundary values ---
    (0x00000000, 0x00000000, 3, "OR: zero | zero = zero"),
    (0x80000000, 0x7FFFFFFF, 3, "OR: min_neg | max_pos = all_ones"),
    (0xFFFFFFFF, 0x00000001, 3, "OR: all_ones | one = all_ones"),
    (0x00000001, 0x80000000, 3, "OR: one | min_neg, negative result"),
    (0xA5A5A5A5, 0x5A5A5A5A, 3, "OR: alternating patterns = all_ones"),

    # --- XOR tests ---
    (0xFFFFFFFF, 0xFFFFFFFF, 4, "XOR: all_ones ^ all_ones = zero"),
    (0x00000000, 0xFFFFFFFF, 4, "XOR: zero ^ all_ones = all_ones"),
    (0x80000000, 0x00000001, 4, "XOR: min_neg ^ one"),
    (0x7FFFFFFF, 0x80000000, 4, "XOR: max_pos ^ min_neg = all_ones"),
    (0x00000001, 0x00000001, 4, "XOR: one ^ one = zero"),

    # --- SLL shift boundary tests ---
    (0x00000001, 0x00000000, 5, "SLL: shift 1 by 0, no change"),
    (0x00000001, 0x0000001F, 5, "SLL: shift 1 by 31, becomes min_neg"),
    (0x80000000, 0x00000001, 5, "SLL: shift min_neg by 1, becomes zero"),
    (0xFFFFFFFF, 0x00000001, 5, "SLL: shift all_ones by 1"),
    (0x7FFFFFFF, 0x0000001F, 5, "SLL: shift max_pos by 31"),

    # --- SRL shift boundary tests ---
    (0x80000000, 0x0000001F, 6, "SRL: shift min_neg right by 31, becomes 1"),
    (0xFFFFFFFF, 0x00000001, 6, "SRL: logical right shift all_ones by 1"),
    (0x00000001, 0x00000001, 6, "SRL: shift 1 right by 1, becomes zero"),
    (0x80000000, 0x00000000, 6, "SRL: shift min_neg by 0, no change"),
    (0x7FFFFFFF, 0x0000001F, 6, "SRL: shift max_pos right by 31, becomes zero"),

    # --- SRA shift boundary tests ---
    (0x80000000, 0x0000001F, 7, "SRA: arithmetic shift min_neg by 31, becomes all_ones"),
    (0x7FFFFFFF, 0x0000001F, 7, "SRA: arithmetic shift max_pos by 31, becomes zero"),
    (0xFFFFFFFF, 0x00000001, 7, "SRA: arithmetic shift all_ones by 1, stays all_ones"),
    (0x80000000, 0x00000001, 7, "SRA: arithmetic shift min_neg by 1, sign extends"),
    (0x00000001, 0x00000000, 7, "SRA: shift 1 by 0, no change"),

    # --- SLT signed comparison edge cases ---
    (0xFFFFFFFF, 0x00000001, 8, "SLT: -1 < 1 signed, result = 1"),
    (0x00000001, 0xFFFFFFFF, 8, "SLT: 1 < -1 signed, result = 0"),
    (0x80000000, 0x7FFFFFFF, 8, "SLT: min_neg < max_pos signed, result = 1"),
    (0x7FFFFFFF, 0x80000000, 8, "SLT: max_pos < min_neg signed, result = 0"),
    (0x00000000, 0x00000000, 8, "SLT: zero < zero, result = 0"),

    # --- SLTU unsigned comparison edge cases ---
    (0xFFFFFFFF, 0x00000001, 9, "SLTU: max_unsigned < 1, result = 0 (opposite of SLT)"),
    (0x00000001, 0xFFFFFFFF, 9, "SLTU: 1 < max_unsigned, result = 1 (opposite of SLT)"),
    (0x80000000, 0x7FFFFFFF, 9, "SLTU: 0x80000000 > 0x7FFFFFFF unsigned, result = 0"),
    (0x00000000, 0x00000001, 9, "SLTU: zero < one, result = 1"),
    (0x7FFFFFFF, 0x80000000, 9, "SLTU: max_pos < min_neg unsigned, result = 1"),
]


def get_ai_tests():
    tests = []
    for a, b, op, desc in AI_GENERATED_TESTS:
        tests.append(TestVector(a & MASK_32, b & MASK_32, op, desc))
    return tests


# =============================================================================
# Live AI Generation (optional, requires API key)
# =============================================================================

ALU_SPEC_PROMPT = """You are a hardware verification engineer. Generate test vectors for a 32-bit RISC-V RV32I ALU.

The ALU supports these operations:
- 0: ADD (32-bit addition)
- 1: SUB (32-bit subtraction)
- 2: AND (bitwise AND)
- 3: OR (bitwise OR)
- 4: XOR (bitwise XOR)
- 5: SLL (shift left logical, shift amount = operand_b[4:0])
- 6: SRL (shift right logical, shift amount = operand_b[4:0])
- 7: SRA (shift right arithmetic, shift amount = operand_b[4:0])
- 8: SLT (set less than, signed comparison)
- 9: SLTU (set less than, unsigned comparison)

The ALU generates flags: zero, carry (ADD/SUB only), overflow (signed, ADD/SUB only), negative.

Generate {num_tests} test vectors that maximise functional coverage. Focus on:
- Boundary values: 0x00000000, 0xFFFFFFFF, 0x7FFFFFFF, 0x80000000, 0x00000001
- Signed overflow and underflow conditions
- Carry generation scenarios
- Shift boundary cases (shift by 0, 1, 31)
- Signed vs unsigned comparison differences (SLT vs SLTU)
- Each ALU operation should be tested with different operand categories

Respond ONLY with a JSON array. No other text, no markdown backticks. Each element must have:
- "operand_a": integer (decimal)
- "operand_b": integer (decimal)
- "alu_op": integer (0-9)
- "description": short string explaining what the test targets

Example format:
[{{"operand_a": 2147483647, "operand_b": 1, "alu_op": 0, "description": "ADD: max positive + 1, triggers signed overflow"}}]
"""


def generate_live_ai_tests(num_tests=50):
    try:
        import google.generativeai as genai
    except ImportError:
        print("Error: google-generativeai package not installed.")
        print("Run: python -m pip install google-generativeai")
        sys.exit(1)

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY environment variable not set.")
        print("Get a free key from https://aistudio.google.com/apikey")
        print("Then run: $env:GEMINI_API_KEY='your-key-here'")
        sys.exit(1)

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-2.0-flash")
    print(f"Requesting {num_tests} test vectors from Gemini API...")

    response = model.generate_content(ALU_SPEC_PROMPT.format(num_tests=num_tests))
    response_text = response.text.strip()
    if response_text.startswith("```"):
        response_text = response_text.split("\n", 1)[1]
        response_text = response_text.rsplit("```", 1)[0]

    try:
        raw_tests = json.loads(response_text)
    except json.JSONDecodeError as e:
        print(f"Error parsing AI response: {e}")
        sys.exit(1)

    tests = []
    for t in raw_tests:
        try:
            tv = TestVector(
                operand_a=int(t["operand_a"]) & MASK_32,
                operand_b=int(t["operand_b"]) & MASK_32,
                alu_op=int(t["alu_op"]),
                description=t.get("description", "")
            )
            if 0 <= tv.alu_op <= 9:
                tests.append(tv)
        except (KeyError, ValueError) as e:
            print(f"  Skipping malformed test: {e}")

    print(f"Successfully parsed {len(tests)} test vectors from Gemini API.\n")
    return tests


# =============================================================================
# Random Test Generator (mirrors UVM constrained random)
# =============================================================================

def generate_random_tests(num_tests=50):
    tests = []
    for _ in range(num_tests):
        r = random.random()
        if r < 0.05:     a = 0x00000000
        elif r < 0.10:   a = 0xFFFFFFFF
        elif r < 0.15:   a = 0x80000000
        elif r < 0.20:   a = 0x7FFFFFFF
        elif r < 0.60:   a = random.randint(0x00000001, 0x7FFFFFFE)
        else:             a = random.randint(0x80000001, 0xFFFFFFFE)

        r = random.random()
        if r < 0.05:     b = 0x00000000
        elif r < 0.10:   b = 0xFFFFFFFF
        elif r < 0.15:   b = 0x80000000
        elif r < 0.20:   b = 0x7FFFFFFF
        elif r < 0.60:   b = random.randint(0x00000001, 0x7FFFFFFE)
        else:             b = random.randint(0x80000001, 0xFFFFFFFE)

        op = random.randint(0, 9)
        tests.append(TestVector(a, b, op, "constrained random"))
    return tests


# =============================================================================
# Comparison Report
# =============================================================================

def run_comparison(ai_tests, random_tests):
    print("=" * 70)
    print("  AI vs CONSTRAINED RANDOM — COVERAGE COMPARISON")
    print("=" * 70)

    ai_cov = CoverageTracker()
    for tv in ai_tests:
        ai_cov.sample(tv)
    ai_report = ai_cov.get_report()

    rnd_cov = CoverageTracker()
    for tv in random_tests:
        rnd_cov.sample(tv)
    rnd_report = rnd_cov.get_report()

    print(f"\n{'Metric':<30} {'AI (' + str(len(ai_tests)) + ' tests)':<25} {'Random (' + str(len(random_tests)) + ' tests)':<25}")
    print("-" * 80)

    metrics = [
        ("Operation Coverage", "operation_coverage", "op_bins_hit"),
        ("Operand A Coverage", "operand_a_coverage", "opa_bins_hit"),
        ("Operand B Coverage", "operand_b_coverage", "opb_bins_hit"),
        ("Flag Coverage", "flag_coverage", None),
        ("Cross: Op x OpA", "cross_op_x_opa", "cross_opa_hit"),
        ("Cross: Op x OpB", "cross_op_x_opb", "cross_opb_hit"),
    ]

    for label, pct_key, bin_key in metrics:
        ai_pct = ai_report[pct_key]
        rnd_pct = rnd_report[pct_key]
        if bin_key:
            ai_str = f"{ai_pct:6.1f}%  ({ai_report[bin_key]})"
            rnd_str = f"{rnd_pct:6.1f}%  ({rnd_report[bin_key]})"
        else:
            ai_str = f"{ai_pct:6.1f}%"
            rnd_str = f"{rnd_pct:6.1f}%"
        winner = " <-- AI" if ai_pct > rnd_pct else " <-- Random" if rnd_pct > ai_pct else " (tie)"
        print(f"{label:<30} {ai_str:<25} {rnd_str:<25}{winner}")

    # AI test details
    print(f"\n{'=' * 70}")
    print("  AI-GENERATED TEST DETAILS")
    print("=" * 70)

    for i, tv in enumerate(ai_tests):
        v = tv.verify()
        print(f"\n  Test {i+1}: {v['description']}")
        print(f"    {v['op']}: A={v['op_a']}, B={v['op_b']} -> Result={v['result']}")
        print(f"    Flags: zero={v['zero']}, overflow={v['overflow']}, carry={v['carry']}, negative={v['negative']}")

    # Summary
    print(f"\n{'=' * 70}")
    print("  ANALYSIS SUMMARY")
    print("=" * 70)

    ai_cross = (ai_report["cross_op_x_opa"] + ai_report["cross_op_x_opb"]) / 2
    rnd_cross = (rnd_report["cross_op_x_opa"] + rnd_report["cross_op_x_opb"]) / 2

    print(f"\n  AI average cross coverage:     {ai_cross:.1f}%")
    print(f"  Random average cross coverage: {rnd_cross:.1f}%")

    if ai_cross > rnd_cross:
        print(f"\n  AI-generated tests achieved {ai_cross - rnd_cross:.1f}% higher cross coverage")
        print(f"  with {len(ai_tests)} tests vs {len(random_tests)} random tests.")
        print(f"  This demonstrates that targeted AI stimulus can reach coverage")
        print(f"  goals more efficiently than purely random approaches.")
    elif rnd_cross > ai_cross:
        print(f"\n  Random tests achieved {rnd_cross - ai_cross:.1f}% higher cross coverage.")
        print(f"  Constrained random naturally explores the design space broadly,")
        print(f"  while AI may over-focus on known corner cases.")
    else:
        print(f"\n  Both approaches achieved equal cross coverage.")

    print(f"\n  Conclusion: The most effective verification combines AI-targeted")
    print(f"  corner cases with constrained random breadth — which is exactly")
    print(f"  what the alu_full_test does by running directed tests first,")
    print(f"  then flooding with random stimulus.\n")

    return ai_report, rnd_report


# =============================================================================
# Export to SystemVerilog
# =============================================================================

def export_sv_stimulus(tests, filename="ai_stimulus.sv"):
    filepath = os.path.join(os.path.dirname(os.path.abspath(__file__)), filename)
    with open(filepath, "w") as f:
        f.write("// Auto-generated AI test stimulus for RISC-V ALU\n")
        f.write(f"// {len(tests)} test vectors generated by Claude (Anthropic)\n")
        f.write("// These can be included in a UVM sequence body() task\n\n")
        for i, tv in enumerate(tests):
            f.write(f"// Test {i+1}: {tv.description}\n")
            f.write(f"item = alu_seq_item::type_id::create(\"item\");\n")
            f.write(f"start_item(item);\n")
            f.write(f"item.operand_a = 32'h{tv.operand_a:08X};\n")
            f.write(f"item.operand_b = 32'h{tv.operand_b:08X};\n")
            f.write(f"item.alu_op    = 4'd{tv.alu_op};\n")
            f.write(f"finish_item(item);\n\n")
    print(f"Exported SystemVerilog stimulus to: {filepath}")


# =============================================================================
# Main
# =============================================================================

def main():
    print("\n" + "=" * 70)
    print("  RISC-V ALU — AI-ASSISTED TEST GENERATION")
    print("=" * 70 + "\n")

    # Check for live mode
    live_mode = "--live" in sys.argv
    
    if live_mode:
        print("Running in LIVE mode — calling Gemini API...\n")
        ai_tests = generate_live_ai_tests(num_tests=50)
    else:
        print("Using pre-generated AI test vectors (generated by Claude).")
        print("Run with --live flag and GEMINI_API_KEY to generate fresh tests.\n")
        ai_tests = get_ai_tests()

    # Generate same number of random tests for fair comparison
    random_tests = generate_random_tests(num_tests=len(ai_tests))

    # Run comparison
    ai_report, rnd_report = run_comparison(ai_tests, random_tests)

    # Export AI tests as SystemVerilog
    export_sv_stimulus(ai_tests)

    # Save results as JSON
    results_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "results.json")
    results = {
        "mode": "live" if live_mode else "pre-generated",
        "ai_test_count": len(ai_tests),
        "random_test_count": len(random_tests),
        "ai_coverage": ai_report,
        "random_coverage": rnd_report,
        "ai_tests": [tv.verify() for tv in ai_tests]
    }
    with open(results_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"Saved detailed results to: {results_path}\n")


if __name__ == "__main__":
    main()